variable "stack_name" {}
variable "ecs_cluster_id" {}
variable "docker_name" {}
variable "desired_count" {}
variable "conduit_secret" {}
variable "container_port" {}
variable "docker_cpu" {}
variable "docker_memory" {}
variable "docker_version" {}
variable "ecr_account" {}
variable "ecr_region" {}
variable "flask_app" {}
variable "flask_debug" {}
variable "host_port" {}
variable "network_mode" {}
