variable "ami_id" {}
variable "asg_desired" {}
variable "asg_force_delete" {}
variable "asg_max" {}
variable "asg_min" {}
variable "assign_public_ip" {}
variable "cidr" {}
variable "environment_type" {}
variable "flask_port" {}
variable "instance_type" {}
variable "key_name" {}
variable "propagate_at_launch" {}
variable "public_subnet" {}
variable "ssh_port" {}
variable "stack_name" {}
variable "volume_size" {}
variable "volume_type" {}
variable "vpc_id" {}
variable "nginx_port" {}
variable "node_port" {}
variable "https_port" {}
variable "ssl_bucket" {}
variable "ssl_bucket_arn" {}
